apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-registry
spec:
  tls:
    - hosts:
        - "{{ .Values.service.registry.ingress }}"
      secretName: tls-registry
  rules:
    - host: "{{ .Values.service.registry.ingress }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gitlab
                port:
                  number: {{ .Values.service.registry.port }}
