apiVersion: v1
kind: Service
metadata:
  labels:
    com.github.thetredev.gitlab-helm-simple.service: gitlab
  name: gitlab
spec:
  type: LoadBalancer
  loadBalancerIP: "{{ .Values.network.ip }}"
  ports:
    # https
    - name: "{{ .Values.service.https.name }}"
      protocol: "{{ .Values.service.https.protocol }}"
      port: {{ .Values.service.https.port }}
      targetPort: {{ .Values.service.https.port }}
    # registry
    - name: "{{ .Values.service.registry.name }}"
      protocol: "{{ .Values.service.registry.protocol }}"
      port: {{ .Values.service.registry.port }}
      targetPort: {{ .Values.service.registry.port }}
    # ssh
    - name: "{{ .Values.service.ssh.name }}"
      protocol: "{{ .Values.service.ssh.protocol }}"
      port: {{ .Values.service.ssh.port }}
      targetPort: {{ .Values.service.ssh.port }}
  selector:
    com.github.thetredev.gitlab-helm-simple.service: gitlab
